### ISSUE TITLE
the plugin does not start if there is geyser-spigot

### ISSUE THREAD

**Issue by haroldrc** [PimvanderLoos/AnimatedArchitecture#115]

**Comment by PimvanderLoos** [comment]
This is by design.

Either GeyserMC or the bedrock client does not handle the falling blocks used during the animations as intended. As such, to avoid issues, the plugin will refuse to start. For this same reason, it also won't start when ViaRewind is used (as old clients don't understand the entities being used) or when running on unsupported servers (CatServer, Mohist, etc).

If you want to ignore the issues and force the plugin to start anyway, you can enable the `unsafeMode` option in the config. Please read the warnings above the option.
