### ISSUE TITLE
[Feature] Crane

### ISSUE THREAD

**Issue by JaHollTV** [PimvanderLoos/AnimatedArchitecture#173]
![bigdoors-crane](https://user-images.githubusercontent.com/48917504/191362880-210ea505-ffdf-4220-bbb6-6bd3f5ee8fe5.PNG)
Hey there,
as shown in the Image i want to request a "Crane-Door".
This door has 2 new abilities:
1) it's like a sliding-door, but the rotation-block / swing-block is not in the corner of the selection (the iron block)
2) it's like a sliding-door, but it rotates a whole level / layer (yellow concrete, gray concrete and the iron block)

Then you can build cranes with more then 1 block width

Would be very awesome!
An API-Method to Rotate Selections (like i select with worldedit) and rotate this through a point / or example given by coordinates would be the base of this crane-door and for me and testing absolute enough.

**Comment by PimvanderLoos** [comment]
Hi!
Do you mean a drawbridge perhaps? As the sliding-door type does not rotate.

Regardless, both drawbridges and regular doors no longer have the requirement that they can be only 1 block deep and that the rotation point needs to be in a specific place. This is also why the new windmill type works, as shown in this (heavily compressed) [video](https://i.imgur.com/N9TBKk4.gif). Or another example for [regular doors](https://i.imgur.com/iZre31K.mp4). Perhaps that is what you are looking for?

And regarding the API, that is indeed something I'd like to make at some point. However, it has already taken too long to get this project released, so it's something that will have to wait until after an initial version has been released.

My ultimate goal is to have a complete animation system, where you can create keyframes for animated objects and everything. I'd really like to be able to create animations for things like [this](https://youtu.be/vA0ejYk1s4k). This would become its own project separate from BigDoors and I'd probably split up BigDoors into the animation core and the door-related stuff. The core would then have all the APIs to be able to rotate arbitrary blocks and stuff. The extension system will also have to be completely rewritten, but that is a worry for later. As I said, I want to release it first ;)


p.s. I keep wiping my screen because of that black spot on the image :D
