### ISSUE TITLE
[Request] Developer Documentation, Javadocs and build instructions for bigdoors-doors

### ISSUE THREAD

**Issue by JaHollTV** [PimvanderLoos/AnimatedArchitecture#176]
Hey,
i want to test and hopefully improve the bigdoors-doors like a garagedoor.
Sadly, i do not understand, how i can compile bigdoors-doors and use it with bigdoors?
Therefore, a readme or little developer instructions would be awesome.
I also want to ask for some javadocs.

**Comment by PimvanderLoos** [comment]
Hey!

The javadocs can be found [here](https://pimvanderloos.github.io/BigDoors/javadoc/). The packages themselves aren't annotated yet, but many methods are.

There's no readme because I don't think this project is ready for use yet ;)
I've recently been trying to focus more on getting the project ready rather than adding every feature I can think of.
One of the things you need to keep in mind is that this project is built for MC 1.15, but uses a much newer version of Java than the Spigot build allows. I got around this issue by modifying the Spigot jar using [Recaf](https://github.com/Col-E/Recaf) to remove the Java version check (I don't think Paper had the flag to bypass the check yet in 1.15.)

If that hasn't scared you off, you can build the project (including the doors) with `mvn clean package` for the top-level pom. To run all the tests etc you can run `mvn clean -P=errorprone test package checkstyle:checkstyle pmd:check`. Note that project depends on the NMS packages for 1.15.2, so if you don't have those yet, you'll need to run BuildTools for that version first.

To use the generated door jars, you put them in the `{server}/plugins/BigDoors2/Extensions/` folder. The plugin will load the jars from there on startup.

**Comment by drakosoldier298** [comment]
seems the java docs have been removed.

**Comment by PimvanderLoos** [comment]
The name of the project was changed from BigDoors to AnimatedArchitecture. The link above still points to the BigDoors repository. The docs are now available [here](https://pimvanderloos.github.io/AnimatedArchitecture/javadoc/). The link at the bottom of the README should always point to the correct location (in case it's moved again for some reason).

Also, the installation instructions I posted above aren't fully up-to-date anymore either. You can find the latest instructions for compiling and installing the plugin in the README.
