### ISSUE TITLE
Only Flag and Garage Door structures are working in 0.5

### ISSUE THREAD

**Issue by CammiePone** [PimvanderLoos/AnimatedArchitecture#551]
I don't know why, there doesn't appear to be any errors in the log, but only the garage door and flag structures are loading from the jars. I really was hoping for the windmill and clock structures since they'd be amazing additions to a server im building, but they don't seem to be loading when the server it restarted :/

**Comment by CammiePone** [comment]
I really hope this is just a me issue, and not a mod issue. if I'm doing something wrong, I'd really like to know

**Comment by CammiePone** [comment]
oooh i think i see what the issue is. drawbridge is required for windmill, and windmill is required for clock, but because im using big doors for drawbridges since i get physics with an addon to that, i dont get windmills or clocks unless i include the drawbridge from this one too

**Comment by CammiePone** [comment]
yup! that was it! user error in the end, didnt realise that the structures relied on one another until i checked the manifest.md files in the jars. sorry for possibly wasting your time

**Comment by PimvanderLoos** [comment]
Hey! 
I'm glad the issue has been resolved, and I apologize for not getting to you sooner.

The structures do indeed have dependencies between some of the types, but I don't think this is currently documented anywhere :flushed: 

I'm considering dropping the whole idea of publishing the structures as separate jars for version 0.7. It's been more of a hassle for users (and regularly myself) than it's worth. I might keep the jar loader and everything in place in case anyone wants to use it to add custom structure types, but the default 9 will likely be part of the main jar instead.

Maybe in the far future, I'll offer them as separate jars again, but only when/if the interfaces are much more stable, so you only rarely have to update the structures themselves rather than with every core update. I still like the idea of creating a marketplace (perhaps Modrinth/Hangar) where you can download the specific types you wish, with commands to download/update them in-game as well.

For now, I'll try to update the logging so it's clearer what is going on when there are missing dependencies. I'll make sure that makes it into version 0.6, which will be a relatively minor bugfix release.

---

EDIT: Btw, if you're going to play around with clocks, you should grab a recent build of 0.6-SNAPSHOT from the actions tab. There's a bug with its creator in 0.5 that was fixed in #499.

**Comment by CammiePone** [comment]
ah! so im not crazy for clocks being funky! glad to hear that!
