### ISSUE TITLE
[BUG] Not all blocks are rotating

### ISSUE THREAD

**Issue by ytcalifax** [PimvanderLoos/AnimatedArchitecture#645]
It seems that not all of the blocks are rotated, even though they are a part of the selection (in my case - trap doors and grind stones). Is this a bug or is it some kind of a limitation regarding non-solid blocks?

**Comment by PimvanderLoos** [comment]
Thank you for your report. I'm not entirely sure why these blocks don't rotate properly. I'll have to investigate that when I have time.

**Comment by PimvanderLoos** [comment]
This issue is resolved in release 0.6.

There are still some types of blocks that are not allowed. You can see what isn't allowed [HERE](https://github.com/PimvanderLoos/AnimatedArchitecture/blob/bd7c6514eee6df0d39629678c8e1f0b4df95e356/animatedarchitecture-spigot/spigot-v1_21/src/main/java/nl/pim16aap2/animatedarchitecture/spigot/v1_21/BlockAnalyzer_V1_21.java).

Basically, blocks with additional data such as an inventory (chests, furnaces, etc), patterns (banners), text (signs), etc are not allowed.

I am working on supporting all of that in the block-state branch. Currently, it's all working fine. I just need to add these data to the recovery system (so an unfortunately timed server crash won't clear the contents of a chest).

Additionally, I am aware of an issue with certain types of blocks are invisible during the animation (e.g. heads, banners, signs, and more). This will be fixed in a future release.

Because the original issue has been resolved (trapdoors and grindstones work fine now), I'll go ahead and close this issue.
