### ISSUE TITLE
[Bug]: Double-Drop-Block-Elemente

### ISSUE THREAD

**Issue by ErythroCraft** [PimvanderLoos/AnimatedArchitecture#88]
Please watch out the video to understand. **Rails are white-listed, but the rails will drop.**

https://user-images.githubusercontent.com/76217862/160786267-14e26db1-866d-46cf-bc20-4f29e4122f1b.mp4

**Maybe you can fix this.**

**Comment by PimvanderLoos** [comment]
Yeah, that's why they are blacklisted by default. The whitelist should only be used to override materials when the downsides are known and worth it. The whitelist was originally added because someone needed to use chests/furnaces in a door and didn't care that any items inside would get dropped when the door starts.

The goal is to eventually allow materials such as rails and torches to be used in v2 once that's done, but there are currently no plans for v1.

**Comment by ErythroCraft** [comment]
ok

**Comment by PimvanderLoos** [comment]
While looking into the issue a bit more, I realized that the solution was much easier than I'd thought initially. I've now started work on getting this in v1 as well, as I think it'd be quite nice to be able to use torches and rails etc in doors.

**Comment by PimvanderLoos** [comment]
I've published a [new dev-build](https://pim16aap2.nl/BigDoors/b1094/) that allows certain types of attached blocks (including rails) to be part of doors by default on 1.18+. They will no longer be duplicated as shown in the video and they will be rotated properly when needed.
